# Generated by Django 3.1.6 on 2021-02-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Surname', models.CharField(max_length=20)),
                ('Field', models.CharField(max_length=20)),
                ('Institution', models.CharField(max_length=20)),
                ('Interest', models.TextField()),
            ],
        ),
    ]
