# Generated by Django 3.1.6 on 2021-02-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Applications',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
    ]
