# Generated by Django 3.1.6 on 2021-02-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_applications'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Email',
            field=models.EmailField(default='t@gmai.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='Password',
            field=models.TextField(default=12345),
            preserve_default=False,
        ),
    ]
