# Generated by Django 3.1.6 on 2021-02-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20210218_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Password',
            field=models.CharField(max_length=50),
        ),
    ]
